"""create sheets and sheet_lines tables

Revision ID: 014e91ed79fd
Revises: f55df08e7476
Create Date: 2026-05-27 04:57:08.876501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014e91ed79fd'
down_revision: Union[str, Sequence[str], None] = 'f55df08e7476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'FINISHED', name='sheetstatus'), nullable=False),
    sa.Column('cost_proxy', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_sms', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_bot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_fintech', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sheet_id', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('deposit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('withdrawal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('chest', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('result', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sheet_lines')
    op.drop_table('sheets')
    # ### end Alembic commands ###
