"""add goal field to sheets

Revision ID: ac0c46c24582
Revises: 014e91ed79fd
Create Date: 2026-05-29 17:46:23.131672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0c46c24582'
down_revision: Union[str, Sequence[str], None] = '014e91ed79fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheets', sa.Column('goal', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheets', 'goal')
    # ### end Alembic commands ###
