"""drop_cost_columns_from_sheets

Revision ID: d03831f8b7e8
Revises: dcf3f7994074
Create Date: 2026-06-21 01:51:34.440597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03831f8b7e8'
down_revision: Union[str, Sequence[str], None] = 'dcf3f7994074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheets', 'cost_proxy')
    op.drop_column('sheets', 'cost_bot')
    op.drop_column('sheets', 'cost_fintech')
    op.drop_column('sheets', 'cost_sms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheets', sa.Column('cost_sms', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('sheets', sa.Column('cost_fintech', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('sheets', sa.Column('cost_bot', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('sheets', sa.Column('cost_proxy', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
