"""add_bonus_to_sheet_lines

Revision ID: dada5ee85603
Revises: 939b97256862
Create Date: 2026-06-21 16:40:33.297154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dada5ee85603'
down_revision: Union[str, Sequence[str], None] = '939b97256862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheet_lines', sa.Column('bonus', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheet_lines', 'bonus')
    # ### end Alembic commands ###
