"""add platform_id to sheets

Revision ID: dcf3f7994074
Revises: 741f1a3d01ee
Create Date: 2026-06-12 23:51:50.690120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf3f7994074'
down_revision: Union[str, Sequence[str], None] = '741f1a3d01ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheets', sa.Column('platform_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'sheets', 'platforms', ['platform_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sheets', type_='foreignkey')
    op.drop_column('sheets', 'platform_id')
    # ### end Alembic commands ###
